---
title: "R Notebook"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: true
    theme: yeti
  html_notebook:
    toc: true
    toc_float: true
    theme: yeti
---

<center>

**R Seminar** <br>
**Syllabus & Course Schedule** <br>
**Semester**<br>



```{r, echo = FALSE, message = FALSE}

library(data.table)
library(knitr)
library(kableExtra)
library(tidyverse)

infor <- data.table::transpose(infor <- data.frame(`Room:` = c("Room #"),
           `Time:`   = c("Time"), 
           `Instructor:` = c("Neil Yetz, M.P.H."),
           `Office:` = c("Behavioral Sciences Building Office 344"),
           `Office Hours` = c("Time1 - Time2"),
           `Contact` = c("Neil.Yetz@colostate.edu")
           ))

base::rownames(infor) <- c("**Room:**", "**Time:**", "**Instructor:**", "**Office:**", "**Office Hours:**", "**Contact:**")

knitr::kable(infor, col.names = "", format = "html") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)


```
</center>




# Course Information

The purpose of this course is to provide you with an in depth understanding of R, R-studio, & R-notebooks. This course assumes the student has *NO PRIOR KNOWLEDGE* with R prior to the course.


# Course Schedule

```{r, echo = FALSE}
a <- data.frame(date = c("Date 1",
                         "Date 2",
                         "Date 3", 
                         "Date 4",
                         "Date 5",
                         "Date 6"),
                level = c(
                          rep("Basic", 2),
                          rep("Intermediate", 2),
                          rep("Advanced", 2)
                          ),
                content = c("R Preliminaries",
                            "Using the tidyverse",
                            "Visualization & Graphics",
                            "",
                            "",
                            ""), 
                due = c("Quiz (W)", 
                        "Quiz (M), HW #1 (W)",
                        "Quiz (M)", 
                        "", 
                        "",
                        ""))


knitr::kable(a, col.names = c("Dates", "Level", "Lecture content", "Graded items"))%>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)
```
























